/**
 * operatorService — lifecycle for autonomous operator proposals.
 *
 * Proposals are generated by scheduled Claude agents (outside this repo).
 * Each proposal is either:
 *   - tier="auto"              → executed immediately, logged only
 *   - tier="approval_required" → SMS sent to owner, YES/NO <shortCode> reply approves/declines
 *
 * This file is plumbing only. All intelligence (what to propose) lives in Claude /schedule.
 */

const prisma = require('../lib/prismaClient');
const logger = require('../lib/logger');
const {
  sendSmsSafely,
  toE164,
  getTwilioCreds,
} = require('./smsService');
const twilio = require('twilio');
const zapier = require('./zapierClient');

// How long a proposal stays open for approval before auto-expiring.
const DEFAULT_TTL_HOURS = Number(process.env.OPERATOR_PROPOSAL_TTL_HOURS || 4);

// Max shortCode digits — 4 gives 10,000 slots per user, easy to type over SMS.
const SHORTCODE_DIGITS = 4;
const SHORTCODE_MAX    = 10 ** SHORTCODE_DIGITS - 1;

/**
 * Pad a number to SHORTCODE_DIGITS with leading zeros.
 */
function padShortCode(n) {
  return String(n).padStart(SHORTCODE_DIGITS, '0');
}

/**
 * Generate the next shortCode for a user.
 * Sequential based on row count, wraps at SHORTCODE_MAX.
 * The @@unique([userId, shortCode]) constraint + retry handles races.
 */
async function nextShortCodeForUser(userId) {
  const count = await prisma.operatorProposal.count({ where: { userId } });
  const n = (count % SHORTCODE_MAX) + 1;
  return padShortCode(n);
}

/**
 * Create a new proposal.
 * Returns the created row. Does NOT send SMS — call sendProposalSms() separately.
 *
 * @param {object} args
 * @param {string} args.userId     - portal User.id
 * @param {string} args.category   - "ad" | "seo" | "client_recovery" | "social_post" | "quote" | "email" | "review_response" | "other"
 * @param {string} args.tier       - "auto" | "approval_required"
 * @param {string} args.summary    - <=160 chars SMS-friendly summary
 * @param {object} args.payload    - full action spec
 * @param {number} [args.ttlHours] - override default 4h expiry
 */
async function createProposal({ userId, category, tier, summary, payload, ttlHours }) {
  if (!userId)   throw new Error('operatorService.createProposal: userId is required');
  if (!category) throw new Error('operatorService.createProposal: category is required');
  if (!tier)     throw new Error('operatorService.createProposal: tier is required');
  if (!summary)  throw new Error('operatorService.createProposal: summary is required');

  const ttl       = Number(ttlHours ?? DEFAULT_TTL_HOURS);
  const expiresAt = new Date(Date.now() + ttl * 3600 * 1000);
  const trimmed   = summary.slice(0, 160);

  // Retry on shortCode collision (rare — one Claude run at a time per user).
  let lastErr = null;
  for (let attempt = 0; attempt < 5; attempt++) {
    const shortCode = await nextShortCodeForUser(userId);
    try {
      const row = await prisma.operatorProposal.create({
        data: {
          userId,
          shortCode,
          category,
          tier,
          summary: trimmed,
          payload: payload || {},
          status: tier === 'auto' ? 'approved' : 'pending',
          expiresAt,
        },
      });
      await logger.info('operator', `Proposal ${shortCode} created (${category}/${tier})`, {
        proposalId: row.id, shortCode, category, tier,
      }, userId);
      return row;
    } catch (err) {
      lastErr = err;
      // P2002 = unique constraint violation → collision on (userId, shortCode)
      if (err?.code !== 'P2002') throw err;
    }
  }
  throw lastErr || new Error('Failed to allocate unique shortCode after 5 attempts');
}

/**
 * Format the SMS body for an approval-required proposal.
 * Kept under 160 chars where possible; Twilio auto-segments if longer.
 */
function formatProposalSmsBody(proposal) {
  return `🌱 #${proposal.shortCode}: ${proposal.summary}\nReply YES ${proposal.shortCode} or NO ${proposal.shortCode}`;
}

/**
 * Send the approval SMS for a pending proposal.
 * Target phone comes from TwilioCredential.notifyPhone (the owner's personal mobile),
 * falling back to env OPERATOR_APPROVER_PHONE.
 */
async function sendProposalSms(proposalId) {
  const proposal = await prisma.operatorProposal.findUnique({ where: { id: proposalId } });
  if (!proposal) throw new Error(`Proposal ${proposalId} not found`);
  if (proposal.tier !== 'approval_required') {
    throw new Error(`Proposal ${proposal.shortCode} is tier=${proposal.tier}, not approval_required`);
  }

  const creds       = await getTwilioCreds(proposal.userId);
  const credRow     = await prisma.twilioCredential.findUnique({ where: { userId: proposal.userId } }).catch(() => null);
  const toRaw       = credRow?.notifyPhone || process.env.OPERATOR_APPROVER_PHONE;

  if (!toRaw) {
    throw new Error(`No approver phone configured — set TwilioCredential.notifyPhone for user ${proposal.userId} or OPERATOR_APPROVER_PHONE env`);
  }
  if (!creds.accountSid || !creds.authToken) {
    throw new Error(`Twilio credentials not configured for user ${proposal.userId}`);
  }

  const to   = toE164(toRaw);
  const body = formatProposalSmsBody(proposal);

  if (process.env.DRY_RUN === 'true') {
    console.log(`[operator] DRY RUN — would SMS approver ${to}: "${body}"`);
    await prisma.operatorProposal.update({
      where: { id: proposalId },
      data:  { smsSentAt: new Date(), smsMessageSid: 'dry-run' },
    });
    return { ok: true, sid: 'dry-run', dryRun: true };
  }

  const client = twilio(creds.accountSid, creds.authToken);
  const result = await sendSmsSafely({
    to,
    from:   creds.fromNumber,
    body,
    client,
    userId: proposal.userId,
  });

  if (result.ok) {
    await prisma.operatorProposal.update({
      where: { id: proposalId },
      data:  { smsSentAt: new Date(), smsMessageSid: result.sid },
    });
  } else {
    await logger.error('operator', `Proposal ${proposal.shortCode} SMS send failed`, {
      proposalId, errorCode: result.errorCode, errorMessage: result.errorMessage, permanent: !!result.permanent,
    }, proposal.userId);
  }
  return result;
}

/**
 * List pending, non-expired proposals for a user.
 * Used by scheduled Midday Ops run to pick up approvals.
 */
async function listPendingForUser(userId) {
  return prisma.operatorProposal.findMany({
    where: {
      userId,
      status:    'pending',
      expiresAt: { gt: new Date() },
    },
    orderBy: { createdAt: 'asc' },
  });
}

/**
 * List proposals that are approved but not yet executed.
 * Scheduled runs call this to see what to dispatch.
 */
async function listApprovedUnexecuted(userId) {
  return prisma.operatorProposal.findMany({
    where: {
      userId,
      status:     'approved',
      executedAt: null,
    },
    orderBy: { respondedAt: 'asc' },
  });
}

/**
 * Parse an inbound SMS body for a YES/NO <shortCode> reply and update the proposal.
 * Returns:
 *   - { matched: true, proposal, action: 'approved'|'declined' } on success
 *   - { matched: true, proposal, action: 'expired' } if code matched but expired
 *   - { matched: false } if body doesn't match the command pattern
 *
 * The webhook handler calls this for EVERY inbound SMS — matched:false means
 * the message should be handled by the existing review-request Y/N flow.
 */
async function matchInboundResponse({ userId, body }) {
  if (!body) return { matched: false };
  const m = String(body).trim().match(/^(yes|y|no|n)\s+(\d{1,4})\b/i);
  if (!m) return { matched: false };

  const action    = m[1].toLowerCase().startsWith('y') ? 'approved' : 'declined';
  const shortCode = padShortCode(parseInt(m[2], 10));

  const proposal = await prisma.operatorProposal.findUnique({
    where: { userId_shortCode: { userId, shortCode } },
  });
  if (!proposal) return { matched: false };
  if (proposal.status !== 'pending') {
    // Already handled — log and treat as matched so the SMS isn't double-routed.
    await logger.info('operator', `Reply for #${shortCode} ignored — status=${proposal.status}`, {
      proposalId: proposal.id, status: proposal.status,
    }, userId);
    return { matched: true, proposal, action: proposal.status };
  }
  if (proposal.expiresAt < new Date()) {
    await prisma.operatorProposal.update({
      where: { id: proposal.id },
      data:  { status: 'expired' },
    });
    return { matched: true, proposal, action: 'expired' };
  }

  const updated = await prisma.operatorProposal.update({
    where: { id: proposal.id },
    data:  {
      status:       action,
      respondedAt:  new Date(),
      respondedVia: 'sms',
    },
  });
  await logger.info('operator', `Proposal #${shortCode} ${action} via SMS`, {
    proposalId: proposal.id, category: proposal.category,
  }, userId);
  return { matched: true, proposal: updated, action };
}

/**
 * Execute an approved (or auto-tier) proposal by dispatching to the right channel.
 *
 * Routing by category:
 *   social_post                    → zapier.post(channel from payload.channel)
 *   email / client_recovery        → zapier.email()
 *   review_response                → zapier.post('gbp') with review reply text
 *   ad / seo / quote / other       → logged only (Claude handles these directly)
 */
async function executeProposal(proposalId) {
  const proposal = await prisma.operatorProposal.findUnique({ where: { id: proposalId } });
  if (!proposal) throw new Error(`Proposal ${proposalId} not found`);
  if (proposal.executedAt) {
    return { ok: true, alreadyExecuted: true, proposal };
  }
  if (proposal.status !== 'approved') {
    throw new Error(`Proposal ${proposal.shortCode} status=${proposal.status}, cannot execute`);
  }

  let result = { ok: true, note: 'logged-only' };
  try {
    const pl = proposal.payload || {};
    switch (proposal.category) {
      case 'social_post': {
        const channel = pl.channel || 'fb';                  // "fb" | "ig" | "gbp"
        result = await zapier.post(channel, pl, { userId: proposal.userId, proposalId });
        break;
      }
      case 'email':
      case 'client_recovery': {
        result = await zapier.email(pl, { userId: proposal.userId, proposalId });
        break;
      }
      case 'review_response': {
        result = await zapier.post('gbp', { ...pl, kind: 'review_reply' }, { userId: proposal.userId, proposalId });
        break;
      }
      case 'ad':
      case 'seo':
      case 'quote':
      case 'other':
      default:
        // Draft-only categories — execution here is just marking done; Claude already produced the artifact.
        result = { ok: true, note: `category=${proposal.category} is draft-only; logged` };
    }

    await prisma.operatorProposal.update({
      where: { id: proposalId },
      data:  { status: 'executed', executedAt: new Date(), result },
    });
    await logger.info('operator', `Proposal #${proposal.shortCode} executed`, {
      proposalId, category: proposal.category, result,
    }, proposal.userId);
    return { ok: true, proposal, result };
  } catch (err) {
    const errResult = { ok: false, error: err.message };
    await prisma.operatorProposal.update({
      where: { id: proposalId },
      data:  { status: 'failed', executedAt: new Date(), result: errResult },
    });
    await logger.error('operator', `Proposal #${proposal.shortCode} execution failed`, {
      proposalId, category: proposal.category, error: err.message,
    }, proposal.userId);
    return { ok: false, proposal, error: err.message };
  }
}

/**
 * Expire pending proposals past their expiresAt.
 * Called by the startOperatorProposalExpiry() cron in server.js.
 */
async function expirePendingProposals() {
  const res = await prisma.operatorProposal.updateMany({
    where:  { status: 'pending', expiresAt: { lt: new Date() } },
    data:   { status: 'expired' },
  });
  if (res.count > 0) {
    await logger.info('operator', `Expired ${res.count} stale proposals`, { count: res.count });
  }
  return res.count;
}

/**
 * Cron wrapper: runs expirePendingProposals every 10 minutes.
 */
function startOperatorProposalExpiry({ intervalMs = 10 * 60 * 1000 } = {}) {
  const tick = async () => {
    try { await expirePendingProposals(); }
    catch (err) {
      console.error('[operator] expiry cron error:', err.message);
    }
  };
  setTimeout(tick, 30_000);                    // first run 30s after boot
  const handle = setInterval(tick, intervalMs);
  console.log(`[operator] proposal expiry cron started (every ${intervalMs / 60000} min)`);
  return handle;
}

/**
 * Normalize a phone number to last-10-digits for approver matching.
 */
function last10(v) {
  return String(v || '').replace(/\D/g, '').slice(-10);
}

/**
 * List the approver phone numbers for a user (last-10-digit form).
 * Pulled from TwilioCredential.notifyPhone + env OPERATOR_APPROVER_PHONE.
 */
async function getApproverPhonesLast10(userId) {
  const out = new Set();
  const cred = await prisma.twilioCredential.findUnique({ where: { userId } }).catch(() => null);
  if (cred?.notifyPhone) {
    const n = last10(cred.notifyPhone);
    if (n) out.add(n);
  }
  if (process.env.OPERATOR_APPROVER_PHONE) {
    const n = last10(process.env.OPERATOR_APPROVER_PHONE);
    if (n) out.add(n);
  }
  return out;
}

/**
 * Top-level handler for an inbound SMS that came from Steph's approver phone.
 * Tries YES/NO <code> first, then slash commands.
 * Returns { matched: bool, type?, action?, command?, proposal? }.
 *
 * Slash commands are not processed here — they're tagged and picked up
 * by the Pulse run via listInboundCommandsSinceLast(). This keeps the
 * webhook path fast (TwiML must return in < 10s or Twilio retries).
 */
async function handleInboundFromSteph({ userId, body }) {
  if (!body) return { matched: false };
  const trimmed = String(body).trim();

  // Try YES/NO <code>
  const yn = await matchInboundResponse({ userId, body: trimmed });
  if (yn.matched) return { matched: true, type: 'yes_no', action: yn.action, proposal: yn.proposal };

  // Try slash command
  const slash = trimmed.match(/^\/(post|quote|save|note)\b/i);
  if (slash) {
    await logger.info('operator', `Slash command /${slash[1].toLowerCase()} received — deferred to Pulse`, {
      bodyPreview: trimmed.slice(0, 80),
    }, userId);
    return { matched: true, type: 'slash', command: slash[1].toLowerCase() };
  }

  return { matched: false };
}

/**
 * Return inbound SMS messages from Steph's approver phone that match a slash command,
 * within the lookback window. Used by the Pulse run.
 */
async function listInboundCommandsSinceLast({ userId, sinceMinutes = 130 }) {
  const since = new Date(Date.now() - sinceMinutes * 60 * 1000);
  const approverLast10s = await getApproverPhonesLast10(userId);
  if (approverLast10s.size === 0) return [];

  const rows = await prisma.inboundSMS.findMany({
    where:   { userId, receivedAt: { gte: since } },
    orderBy: { receivedAt: 'asc' },
  });

  return rows.filter((r) => {
    if (!approverLast10s.has(last10(r.from))) return false;
    return /^\s*\/(post|quote|save|note)\b/i.test(r.body);
  });
}

/**
 * Check whether a given inbound phone number is Steph's approver phone.
 * Used by the inbound-sms webhook to decide whether to route to operator logic.
 */
async function isFromApprover({ userId, fromPhone }) {
  const approverLast10s = await getApproverPhonesLast10(userId);
  return approverLast10s.has(last10(fromPhone));
}

module.exports = {
  createProposal,
  sendProposalSms,
  listPendingForUser,
  listApprovedUnexecuted,
  matchInboundResponse,
  executeProposal,
  expirePendingProposals,
  startOperatorProposalExpiry,
  formatProposalSmsBody,
  padShortCode,
  handleInboundFromSteph,
  listInboundCommandsSinceLast,
  isFromApprover,
  getApproverPhonesLast10,
};
